### PR TITLE
Fixing [code][/code] tags without merge issues

### PR DESCRIPTION
**Pull request by joker314**
Ok, I have also removed the commented out code that does not work since the problem is resolved. Please test this with multiple code tags/image requests though.

### CODE REVIEW

**Comment by Dylan5797** [comment]
@Tymewalk pls come to this thread :package:

**Comment by joker314** [comment]
I've always wondered, what does :package: represent?

**Comment by joker314** [comment]
@Tymewalk @herI think you both have merge power?

**Comment by herohamp** [comment]
Merged!

**Pull request merged**
