### PR TITLE
[code][/code] I fixed it!

### PR DESCRIPTION
**Pull request by joker314**
Absolutely! Yes! I tested it, but I'd like someone to double check! It adds some fun CSS!

Hope this helps you!

### CODE REVIEW

**Comment by joker314** [comment]
bump

**Comment by joker314** [comment]
anybody?

**Comment by Tymewalk** [comment]
Wow! Thanks for the help! :+1: 
I'll merge it once I see what happened, it seems to be having some problems with automatic merge.

**Comment by Dylan5797** [comment]
You might have to add it to the end of `addEmojis()` because `addEmojis()` is only called if the userscript is enabled and it might cause issues if there are no smilies.

**Comment by joker314** [comment]
Really? So will this not get run or not?

Also, it is a for loop that will never run without smiles.

**Comment by joker314** [comment]
Ok, moved it to `addEmojis()`, though I feel that pointless since it gets called before my code gets run anyway

**Comment by joker314** [comment]
I have a fun idea... I'll make a new PR

**Pull request closed without merging**
